version: '3'
services:
    dev:
      build: 
          context: .
          dockerfile: Dockerfile.dev
      ports:
        - "3000:3000"
      volumes:
        - /var/app/node_modules # Dont link this node_modules
        - .:/var/app # Link . to Container /var.app

    test:
      build: 
          context: .
          dockerfile: Dockerfile.dev
      ports:
        - "3000:3000"
      volumes:
        - /var/app/node_modules
        - .:/var/app
      command: ["npm","run","test"]

